pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Final Results
    actions:
      merge:
        method: merge
